// <auto-generated />
using System;
using EstimateArena.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstimateArena.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(EstimateArenaDbContext))]
    [Migration("20261003211347_InicialLobby")]
    partial class InicialLobby
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EstimateArena.Domain.Partidas.Desafio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_desafio");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Explicacion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("explicacion");

                    b.Property<string>("FuenteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("fuente_url");

                    b.Property<string>("Pregunta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("pregunta");

                    b.Property<long>("RespuestaCorrecta")
                        .HasColumnType("bigint")
                        .HasColumnName("respuesta_correcta");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("unidad");

                    b.HasKey("Id")
                        .HasName("pk_desafios");

                    b.HasIndex("Pregunta")
                        .IsUnique()
                        .HasDatabaseName("uq_desafios_pregunta");

                    b.ToTable("desafios", (string)null);
                });

            modelBuilder.Entity("EstimateArena.Domain.Partidas.Jugador", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_jugador");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("FechaIngreso")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("fecha_ingreso");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreNormalizado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nombre_normalizado");

                    b.Property<long>("PartidaId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_partida");

                    b.Property<string>("TokenJugadorHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("token_jugador_hash");

                    b.HasKey("Id")
                        .HasName("pk_jugadores");

                    b.HasIndex("TokenJugadorHash")
                        .IsUnique()
                        .HasDatabaseName("uq_jugadores_token");

                    b.HasIndex("PartidaId", "NombreNormalizado")
                        .IsUnique()
                        .HasDatabaseName("uq_jugadores_nombre_partida");

                    b.ToTable("jugadores", (string)null);
                });

            modelBuilder.Entity("EstimateArena.Domain.Partidas.Partida", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_partida");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CantidadRondas")
                        .HasColumnType("int")
                        .HasColumnName("cantidad_rondas");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("codigo");

                    b.Property<int>("DuracionRondaSegundos")
                        .HasColumnType("int")
                        .HasColumnName("duracion_ronda_segundos");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTimeOffset?>("FechaExpiracion")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)")
                        .HasColumnName("fecha_expiracion");

                    b.Property<int>("MaximoJugadores")
                        .HasColumnType("int")
                        .HasColumnName("maximo_jugadores");

                    b.Property<string>("TokenAnfitrionHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("token_anfitrion_hash");

                    b.Property<long>("VersionEstado")
                        .HasColumnType("bigint")
                        .HasColumnName("version_estado");

                    b.HasKey("Id")
                        .HasName("pk_partidas");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("uq_partidas_codigo");

                    b.HasIndex("TokenAnfitrionHash")
                        .IsUnique()
                        .HasDatabaseName("uq_partidas_token_anfitrion");

                    b.ToTable("partidas", (string)null);
                });

            modelBuilder.Entity("EstimateArena.Domain.Partidas.Ronda", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_ronda");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DesafioId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_desafio");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<int>("Numero")
                        .HasColumnType("int")
                        .HasColumnName("numero_ronda");

                    b.Property<long>("PartidaId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_partida");

                    b.HasKey("Id")
                        .HasName("pk_rondas");

                    b.HasIndex("DesafioId");

                    b.HasIndex("PartidaId", "DesafioId")
                        .IsUnique()
                        .HasDatabaseName("uq_rondas_desafio_partida");

                    b.HasIndex("PartidaId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("uq_rondas_numero_partida");

                    b.ToTable("rondas", (string)null);
                });

            modelBuilder.Entity("EstimateArena.Domain.Partidas.Jugador", b =>
                {
                    b.HasOne("EstimateArena.Domain.Partidas.Partida", "Partida")
                        .WithMany("Jugadores")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("EstimateArena.Domain.Partidas.Ronda", b =>
                {
                    b.HasOne("EstimateArena.Domain.Partidas.Desafio", "Desafio")
                        .WithMany()
                        .HasForeignKey("DesafioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EstimateArena.Domain.Partidas.Partida", "Partida")
                        .WithMany("Rondas")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desafio");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("EstimateArena.Domain.Partidas.Partida", b =>
                {
                    b.Navigation("Jugadores");

                    b.Navigation("Rondas");
                });
#pragma warning restore 612, 618
        }
    }
}
